In [26]:
import numpy as np
dataset = np.array([1,2,3,4,5,6,7,8,9,10])

In [27]:
def split_xy (dataset, time_steps):
    x,y = list(),list()
    for i in range(len(dataset)): # dataset의 갯수만큼 for문을 돌린다.
        end_number = i + time_steps # i + 4 / 4,5,6,7,8,9
        if end_number > len(dataset) -1: # 4~9, 10-1 =9
            break
        tmp_x, tmp_y = dataset[i:end_number], dataset[end_number] # [0 : 4,5,6,7,8,9,10] , [4,5,6,7,8,9,10]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

x,y = split_xy(dataset, 4)
print('x:',x,'\n','y :',y)

x: [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]] 
 y : [ 5  6  7  8  9 10]


In [49]:
import numpy as np
dataset = np.array([1,2,3,4,5,6,7,8,9,10])

In [51]:
def split_xy2(dataset, time_steps, y_column): # y_column 추가 > y값의 원하는 열의 개수를 지정하기 위해
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i +time_steps
        # x_end_number = x값의 끝번호 / i가 0일 때 현재 time_steps가 4이므로 x_end_number은 4
        y_end_number = x_end_number + y_column  # 추가
        # y_column의 개수만큼 추가되어 끝자리를 나타냄 
        # if end_number = i + time_steps
        #    break
        if y_end_number > len(dataset):
            break  # y_end_number 끝이 10이상이 될 경우 = 11이 되면, for 문을 중지함
        tmp_x = dataset[i:x_end_number]
        tmp_y = dataset[x_end_number : y_end_number]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

time_steps = 4
y_column = 2
x,y = split_xy2(dataset, time_steps, y_column)
print('x : ',x,'\n','y:',y)
print( x.shape,y.shape)  # (5, 4) (5, 2)

x :  [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]] 
 y: [[ 5  6]
 [ 6  7]
 [ 7  8]
 [ 8  9]
 [ 9 10]]
(5, 4) (5, 2)


In [97]:
#1. 데이터
import numpy as np
dataset = np.array(range(1, 21))
dataset = dataset.reshape(10,2)


In [98]:
dataset.shape # (10, 3)

(10, 2)

In [99]:
def split_xy3(dataset, time_steps, y_column): 
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column - 1
        
        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, 1:] 
        tmp_y = dataset[x_end_number - 1:y_end_number, 0]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)
x, y = split_xy3(dataset, 3, 2)

# print('x 값 : ', x)
print('y 값 : ', y)



AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [71]:
print(x.shape,y.shape)  # (8, 3, 2) (8, 1)


(8, 3, 2) (8, 1)


NameError: name 'x_end_number' is not defined

In [68]:
y = y.reshape(y.shape[0])
print(y.shape)

(8,)


In [69]:
print(y)

[23 24 25 26 27 28 29 30]


In [74]:
def split_xy3(dataset, time_steps, y_column):
    x,y =list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps 
        y_end_number = x_end_number + y_column -1
        
        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :-1]
        tmp_y = dataset[x_end_number-1 : y_end_number, -1]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)
x, y = split_xy3(dataset, 3, 2)
print(x,y)

[[[ 1 11]
  [ 2 12]
  [ 3 13]]

 [[ 2 12]
  [ 3 13]
  [ 4 14]]

 [[ 3 13]
  [ 4 14]
  [ 5 15]]

 [[ 4 14]
  [ 5 15]
  [ 6 16]]

 [[ 5 15]
  [ 6 16]
  [ 7 17]]

 [[ 6 16]
  [ 7 17]
  [ 8 18]]

 [[ 7 17]
  [ 8 18]
  [ 9 19]]] [[23 24]
 [24 25]
 [25 26]
 [26 27]
 [27 28]
 [28 29]
 [29 30]]
