파이토치의 구성요소
torch: 텐서를 생성하는 라이브러리

torch.autograd: 자동미분 기능을 제공하는 라이브러리

torch.nn: 신경망을 생성하는 라이브러리

torch.multiprocessing: 병럴처리 기능을 제공하는 라이브러리

torch.utils: 데이터 조작 등 유틸리티 기능 제공

torch.legacy(./nn/.optim): Torch로부터 포팅해온 코드

torch.onnx: ONNX(Open Neural Network Exchange)

서로 다른 프레임워크 간의 모델을 공유할 때 사용

텐서 
- 넘파이의 ndarray와 유사
- gpu를 사용한 연산 가속도 가능


In [30]:
import torch
torch.__version__


'1.10.1+cu102'

In [22]:
x = torch.empty(4,2)
print(x)

tensor([[0.7911, 0.8859],
        [0.8132, 1.6774],
        [0.8670, 0.9302],
        [0.2295, 0.5214]])


In [23]:
x = torch.empty(4,2)
print(x)

tensor([[0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 5.9694e-39],
        [1.7375e-04, 2.6447e+20]])


In [24]:
x = torch.zeros(4,2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [25]:
x = torch.tensor([3,2.3])
x

tensor([3.0000, 2.3000])

In [26]:
x= x.new_ones(2,4,dtype=torch.double)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [28]:
x = torch.randn_like(x, dtype=torch.float )
x

tensor([[-1.2067,  0.4243,  0.8509,  0.4112],
        [ 0.0548,  0.1346, -1.0445, -1.7295]])

In [29]:
print(x.size())

torch.Size([2, 4])


In [31]:
x

tensor([[-1.2067,  0.4243,  0.8509,  0.4112],
        [ 0.0548,  0.1346, -1.0445, -1.7295]])

In [35]:
x = torch.rand(2,4)
y = torch.rand(2,4)
print(x)
print(y)
print(x+y)

tensor([[0.9256, 0.6837, 0.9846, 0.0570],
        [0.9759, 0.3740, 0.5551, 0.5646]])
tensor([[0.4368, 0.0567, 0.8209, 0.7956],
        [0.4982, 0.9556, 0.1002, 0.4500]])
tensor([[1.3624, 0.7404, 1.8054, 0.8526],
        [1.4741, 1.3296, 0.6553, 1.0146]])


In [36]:
print(torch.add(x,y))

tensor([[1.3624, 0.7404, 1.8054, 0.8526],
        [1.4741, 1.3296, 0.6553, 1.0146]])


In [37]:
result = torch.empty(2,4)
torch.add(x,y,out=result)
print(result)

tensor([[1.3624, 0.7404, 1.8054, 0.8526],
        [1.4741, 1.3296, 0.6553, 1.0146]])


In [38]:
print(x)
print(y)
y.add_(x)
print(y)

tensor([[0.9256, 0.6837, 0.9846, 0.0570],
        [0.9759, 0.3740, 0.5551, 0.5646]])
tensor([[0.4368, 0.0567, 0.8209, 0.7956],
        [0.4982, 0.9556, 0.1002, 0.4500]])
tensor([[1.3624, 0.7404, 1.8054, 0.8526],
        [1.4741, 1.3296, 0.6553, 1.0146]])


In [41]:
x = torch.Tensor([[1,3,],
                  [5,7]])
y = torch.Tensor([[2,4],
                  [6,8]])
print(x - y)
print(torch.sub(x,y))
print(x.sub(y))

tensor([[-1., -1.],
        [-1., -1.]])
tensor([[-1., -1.],
        [-1., -1.]])
tensor([[-1., -1.],
        [-1., -1.]])


In [42]:
x = torch.Tensor([[1,3,],
                  [5,7]])
y = torch.Tensor([[2,4],
                  [6,8]])
print(x * y)
print(torch.mul(x,y))
print(x.mul(y))

tensor([[ 2., 12.],
        [30., 56.]])
tensor([[ 2., 12.],
        [30., 56.]])
tensor([[ 2., 12.],
        [30., 56.]])


In [43]:
x = torch.Tensor([[1,3,],
                  [5,7]])
y = torch.Tensor([[2,4],
                  [6,8]])
print(x / y)
print(torch.div(x,y))
print(x.div(y))

tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])
tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])
tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])


In [45]:
x = torch.Tensor([[1,3,],
                  [5,7]])
y = torch.Tensor([[2,4],
                  [6,8]])
print(torch.mm(x,y)) # 행렬 곱
print(torch.sub(x,y))
print(x.sub(y))

tensor([[20., 28.],
        [52., 76.]])
tensor([[-1., -1.],
        [-1., -1.]])
tensor([[-1., -1.],
        [-1., -1.]])


In [46]:
print(x)

tensor([[1., 3.],
        [5., 7.]])


In [47]:
print(x[:,1])

tensor([3., 7.])


In [51]:
x = torch.randn(4,5)
y = x.view(20)
z = x.view(5,-1)

print(x)
print(y)
print(z)


tensor([[-1.0917,  0.1028, -0.7288, -1.4977,  0.1590],
        [ 0.2283, -0.8846, -1.3181, -0.1121,  1.4985],
        [-0.2001,  1.3655,  1.6349,  0.6166, -0.2644],
        [ 0.8133,  0.3713, -0.3327,  1.5859, -0.5421]])
tensor([-1.0917,  0.1028, -0.7288, -1.4977,  0.1590,  0.2283, -0.8846, -1.3181,
        -0.1121,  1.4985, -0.2001,  1.3655,  1.6349,  0.6166, -0.2644,  0.8133,
         0.3713, -0.3327,  1.5859, -0.5421])
tensor([[-1.0917,  0.1028, -0.7288, -1.4977],
        [ 0.1590,  0.2283, -0.8846, -1.3181],
        [-0.1121,  1.4985, -0.2001,  1.3655],
        [ 1.6349,  0.6166, -0.2644,  0.8133],
        [ 0.3713, -0.3327,  1.5859, -0.5421]])


In [54]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.3771])
-0.37710681557655334
torch.float32


In [56]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-1.0731])
-1.0730844736099243
torch.float32


In [60]:
tensor = torch.rand(1,3,3)
print(tensor)
tensor.shape

tensor([[[0.7661, 0.6702, 0.8275],
         [0.3743, 0.1274, 0.3112],
         [0.4816, 0.9637, 0.7661]]])


torch.Size([1, 3, 3])

In [61]:
t = tensor.squeeze()  # 즙을 짜다 >> 차원을 축소해준다.  ([1, 3, 3]) > ([3, 3])
print(t)
print(t.shape)

tensor([[0.7661, 0.6702, 0.8275],
        [0.3743, 0.1274, 0.3112],
        [0.4816, 0.9637, 0.7661]])
torch.Size([3, 3])


In [62]:
tensor = torch.rand(1,3,3)
print(tensor)
print(tensor.shape)

tensor([[[0.2854, 0.6024, 0.0052],
         [0.8548, 0.4825, 0.2788],
         [0.8705, 0.4596, 0.9567]]])
torch.Size([1, 3, 3])


In [67]:
t = tensor.unsqueeze(dim=0)
print(t)

tensor([[[[0.2854, 0.6024, 0.0052],
          [0.8548, 0.4825, 0.2788],
          [0.8705, 0.4596, 0.9567]]]])


In [68]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [78]:
a = torch.randn(1,3,3)
b = torch.randn(1,3,3)
print('a,b,',a,b)
c = torch.cat((a,b), dim=0)
print('c',c)
print(c.shape)



a,b, tensor([[[-0.8485, -0.6198, -1.0138],
         [ 0.6524,  1.9700, -0.5484],
         [-0.6696, -0.8726, -0.4605]]]) tensor([[[-1.7770, -0.5420, -1.1710],
         [-0.6981, -0.0857,  0.7953],
         [-0.0607,  0.9694, -0.4955]]])
c tensor([[[-0.8485, -0.6198, -1.0138],
         [ 0.6524,  1.9700, -0.5484],
         [-0.6696, -0.8726, -0.4605]],

        [[-1.7770, -0.5420, -1.1710],
         [-0.6981, -0.0857,  0.7953],
         [-0.0607,  0.9694, -0.4955]]])
torch.Size([2, 3, 3])


In [80]:
tensor = torch.rand(3,6)
t1,t2,t3 = torch.chunk(tensor,3,dim=1)
print(tensor)
print(t1)
print(t2)
print(t3)

tensor([[0.8597, 0.1403, 0.5543, 0.6685, 0.1058, 0.1982],
        [0.1710, 0.0826, 0.1305, 0.8761, 0.0841, 0.8190],
        [0.7191, 0.3510, 0.7268, 0.3222, 0.0488, 0.3424]])
tensor([[0.8597, 0.1403],
        [0.1710, 0.0826],
        [0.7191, 0.3510]])
tensor([[0.5543, 0.6685],
        [0.1305, 0.8761],
        [0.7268, 0.3222]])
tensor([[0.1058, 0.1982],
        [0.0841, 0.8190],
        [0.0488, 0.3424]])


In [81]:
tensor = torch.rand(3,6)
t1,t2 = torch.split(tensor, 3, dim=1)
print(tensor)
print(t1)
print(t2)


tensor([[0.6333, 0.4820, 0.7776, 0.1099, 0.4928, 0.5476],
        [0.1215, 0.1559, 0.0390, 0.2725, 0.0619, 0.3278],
        [0.7219, 0.0395, 0.2690, 0.9045, 0.4667, 0.8252]])
tensor([[0.6333, 0.4820, 0.7776],
        [0.1215, 0.1559, 0.0390],
        [0.7219, 0.0395, 0.2690]])
tensor([[0.1099, 0.4928, 0.5476],
        [0.2725, 0.0619, 0.3278],
        [0.9045, 0.4667, 0.8252]])


In [88]:
a = torch.ones(7)
print(a)

tensor([1., 1., 1., 1., 1., 1., 1.])


In [89]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1. 1. 1.]


In [90]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2. 2. 2.]


In [92]:
import numpy as np
a = np.ones(7)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)


[2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)


In [93]:
import torch

In [94]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([1.0839])
1.0838581323623657
torch.float32


In [96]:
device = torch.device('cuda' if torch.cuda.is_availabel() else 'cpu')

y = torch.ones_like(x, device=device)
x = x.to(device)
z = x+y
print(device)
print(z)
print(z)
print(z.to('cpu', torch.double))

AttributeError: module 'torch.cuda' has no attribute 'is_availabel'

In [3]:
import torch

In [4]:
x = torch.ones(3,3,requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [5]:
y = x+5
print(y)

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)


In [6]:
print(y.grad_fn)

In [7]:
z = y*y*2
out =z.mean()
print(z, out) 

tensor([[72., 72., 72.],
        [72., 72., 72.],
        [72., 72., 72.]], grad_fn=<MulBackward0>) tensor(72., grad_fn=<MeanBackward0>)


In [10]:
a = torch.randn(3,3)
a = ((a*3)/(a-1))
print(a.requires_grad)

a.requires_grad_(True)
print(a.requires_grad_(True))

b= (a*a).sum()
print(b.grad_fn)

False
tensor([[ 0.2805,  1.0556,  1.6407],
        [-8.2536,  1.4984,  9.8198],
        [ 0.3998,  1.1398,  0.4759]], requires_grad=True)


In [11]:
out.backward()
print(x.grad)

tensor([[2.6667, 2.6667, 2.6667],
        [2.6667, 2.6667, 2.6667],
        [2.6667, 2.6667, 2.6667]])


In [12]:
torch.randn(3,requires_grad=True)

y = x*2 
while y.data.norm()<1000:
    y = y*2
print(y)

tensor([[512., 512., 512.],
        [512., 512., 512.],
        [512., 512., 512.]], grad_fn=<MulBackward0>)


In [13]:
v = torch.tensor([0.1,1.0,0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([3]) and output[0] has a shape of torch.Size([3, 3]).

In [14]:
import torch

In [16]:
data = [[1,2],[3,4]]
x_np = torch.tensor(data)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [17]:
import numpy as np
import math

In [20]:
x = np.linspace(-math.pi,math.pi,2000)
y = np.sin(x)
print(x.shape,y.shape)

(2000,) (2000,)


In [22]:
a = np.random.randn()
b = np.random.randn()
c = np.random.randn()
d = np.random.randn()
a,b,c,d,


(-0.4747391994754476,
 2.3228543966741215,
 0.8735080167962913,
 -0.3816618835367902)

In [23]:
learning_rate = 1e-6
for t in range(2000):
    y_pred = a+b*x+c*x**2+d*x**3
    loss = np.square(y_pred - y).sum()
    if t % 100 ==99:
        print(t,loss)

99 28840.110654316057
199 28840.110654316057
299 28840.110654316057
399 28840.110654316057
499 28840.110654316057
599 28840.110654316057
699 28840.110654316057
799 28840.110654316057
899 28840.110654316057
999 28840.110654316057
1099 28840.110654316057
1199 28840.110654316057
1299 28840.110654316057
1399 28840.110654316057
1499 28840.110654316057
1599 28840.110654316057
1699 28840.110654316057
1799 28840.110654316057
1899 28840.110654316057
1999 28840.110654316057


In [25]:
grad_y_pred = 2.0 * (y_pred-y)
grad_a = grad_y_pred.sum()
grad_b = (grad_y_pred*x).sum()
grad_c = (grad_y_pred*x**2).sum()
grad_d = (grad_y_pred*x**3).sum()


In [26]:
a-=learning_rate*grad_a
b-=learning_rate*grad_b
c-=learning_rate*grad_c
d-=learning_rate*grad_d

print(f'Result: y = {a}+{b}+{c} x^2+{d}dx^3')

Result: y = -0.48434664808857536+2.32605567497736+0.8115552334520321 x^2+-0.33726574825178723dx^3


In [2]:
import torch
import torchaudio # 설치필요


In [4]:
import io
import os
import requests
import tarfile

import boto3 # 설치 필요
from botocore import UNSIGNED
import matplotlib.pyplot as plt
from IPython.display import Audio, display

In [1]:
_SAMPLE_DIR = "_sample_data"
SAMPLE_WAV_PATH = os.path.join(_SAMPLE_DIR, '00001')

In [2]:
import torch
import numpy as np

In [3]:
x = torch.empty(5,4)
x

tensor([[1.0194e-38, 1.0469e-38, 1.0010e-38, 8.9081e-39],
        [8.9082e-39, 5.9694e-39, 8.9082e-39, 1.0194e-38],
        [9.1837e-39, 4.6837e-39, 9.9184e-39, 9.0000e-39],
        [1.0561e-38, 1.0653e-38, 4.1327e-39, 8.9082e-39],
        [9.8265e-39, 9.4592e-39, 1.0561e-38, 1.0653e-38]])

In [4]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [5]:
torch.zeros(2)

tensor([0., 0.])

In [6]:
torch.rand(5,6)

tensor([[0.3256, 0.0289, 0.4751, 0.7824, 0.0095, 0.6371],
        [0.0025, 0.4662, 0.6322, 0.6490, 0.5185, 0.5793],
        [0.6582, 0.4892, 0.4871, 0.9939, 0.1942, 0.0390],
        [0.6780, 0.9328, 0.0574, 0.3729, 0.9678, 0.5275],
        [0.3979, 0.9313, 0.5950, 0.6595, 0.3276, 0.7717]])

In [9]:
l = [13,4]
r = np.array([4,56,7])
torch.tensor(l)

tensor([13,  4])

In [10]:
torch.tensor(r)

tensor([ 4, 56,  7], dtype=torch.int32)

In [11]:
x.size()

torch.Size([5, 4])

In [12]:
type(x)

torch.Tensor

In [18]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [14]:
torch.add(x,y)

tensor([[1.3838, 0.7203],
        [1.6343, 0.6227]])

In [22]:
y.add(x)

tensor([[1.4816, 0.3266],
        [1.2257, 0.7006]])

In [23]:
y.add_(x)  # 변수 대체하기 위해 '_' 사용

tensor([[1.4816, 0.3266],
        [1.2257, 0.7006]])

In [24]:
print(y)

tensor([[1.4816, 0.3266],
        [1.2257, 0.7006]])


In [21]:
y[:,1]

tensor([0.2450, 0.6765])

In [25]:
x = torch.rand(8,8)
print(x)

tensor([[0.5942, 0.2136, 0.0646, 0.5913, 0.4445, 0.8263, 0.9547, 0.6631],
        [0.7495, 0.3924, 0.4028, 0.2224, 0.5161, 0.1789, 0.5077, 0.3394],
        [0.9407, 0.6543, 0.6558, 0.7594, 0.4599, 0.8545, 0.6242, 0.7989],
        [0.3419, 0.0320, 0.9349, 0.5169, 0.8084, 0.1131, 0.8281, 0.6109],
        [0.6232, 0.7817, 0.7463, 0.0111, 0.5582, 0.8447, 0.7059, 0.2552],
        [0.5122, 0.0646, 0.1878, 0.2591, 0.7385, 0.1080, 0.5525, 0.0473],
        [0.7840, 0.2525, 0.2003, 0.9739, 0.0839, 0.0023, 0.3729, 0.5253],
        [0.1289, 0.8903, 0.1695, 0.8753, 0.3719, 0.5376, 0.5112, 0.8858]])


In [27]:
x.view(64)

tensor([0.5942, 0.2136, 0.0646, 0.5913, 0.4445, 0.8263, 0.9547, 0.6631, 0.7495,
        0.3924, 0.4028, 0.2224, 0.5161, 0.1789, 0.5077, 0.3394, 0.9407, 0.6543,
        0.6558, 0.7594, 0.4599, 0.8545, 0.6242, 0.7989, 0.3419, 0.0320, 0.9349,
        0.5169, 0.8084, 0.1131, 0.8281, 0.6109, 0.6232, 0.7817, 0.7463, 0.0111,
        0.5582, 0.8447, 0.7059, 0.2552, 0.5122, 0.0646, 0.1878, 0.2591, 0.7385,
        0.1080, 0.5525, 0.0473, 0.7840, 0.2525, 0.2003, 0.9739, 0.0839, 0.0023,
        0.3729, 0.5253, 0.1289, 0.8903, 0.1695, 0.8753, 0.3719, 0.5376, 0.5112,
        0.8858])

In [28]:
x.view(4,16)

tensor([[0.5942, 0.2136, 0.0646, 0.5913, 0.4445, 0.8263, 0.9547, 0.6631, 0.7495,
         0.3924, 0.4028, 0.2224, 0.5161, 0.1789, 0.5077, 0.3394],
        [0.9407, 0.6543, 0.6558, 0.7594, 0.4599, 0.8545, 0.6242, 0.7989, 0.3419,
         0.0320, 0.9349, 0.5169, 0.8084, 0.1131, 0.8281, 0.6109],
        [0.6232, 0.7817, 0.7463, 0.0111, 0.5582, 0.8447, 0.7059, 0.2552, 0.5122,
         0.0646, 0.1878, 0.2591, 0.7385, 0.1080, 0.5525, 0.0473],
        [0.7840, 0.2525, 0.2003, 0.9739, 0.0839, 0.0023, 0.3729, 0.5253, 0.1289,
         0.8903, 0.1695, 0.8753, 0.3719, 0.5376, 0.5112, 0.8858]])

In [30]:
x.view(-1,16,1)

tensor([[[0.5942],
         [0.2136],
         [0.0646],
         [0.5913],
         [0.4445],
         [0.8263],
         [0.9547],
         [0.6631],
         [0.7495],
         [0.3924],
         [0.4028],
         [0.2224],
         [0.5161],
         [0.1789],
         [0.5077],
         [0.3394]],

        [[0.9407],
         [0.6543],
         [0.6558],
         [0.7594],
         [0.4599],
         [0.8545],
         [0.6242],
         [0.7989],
         [0.3419],
         [0.0320],
         [0.9349],
         [0.5169],
         [0.8084],
         [0.1131],
         [0.8281],
         [0.6109]],

        [[0.6232],
         [0.7817],
         [0.7463],
         [0.0111],
         [0.5582],
         [0.8447],
         [0.7059],
         [0.2552],
         [0.5122],
         [0.0646],
         [0.1878],
         [0.2591],
         [0.7385],
         [0.1080],
         [0.5525],
         [0.0473]],

        [[0.7840],
         [0.2525],
         [0.2003],
         [0.9739],
      

In [34]:
y= x.numpy()
y

array([[0.5941649 , 0.21362704, 0.06459856, 0.5913336 , 0.4444502 ,
        0.82634014, 0.9547417 , 0.66312593],
       [0.74945873, 0.39237255, 0.40280795, 0.22237623, 0.5160693 ,
        0.17890614, 0.5076993 , 0.339446  ],
       [0.94070905, 0.65428376, 0.6557749 , 0.7593991 , 0.45986205,
        0.85453683, 0.6241721 , 0.79886794],
       [0.34189236, 0.03197491, 0.9348733 , 0.516884  , 0.80841357,
        0.11307174, 0.82812035, 0.6108662 ],
       [0.6232348 , 0.7817314 , 0.74625707, 0.01111048, 0.5582403 ,
        0.84466684, 0.70593697, 0.25522238],
       [0.5121692 , 0.06458092, 0.18780792, 0.2591375 , 0.7384654 ,
        0.10797185, 0.55252594, 0.04732877],
       [0.78401184, 0.2525339 , 0.20027876, 0.9738588 , 0.08385247,
        0.00227743, 0.37286824, 0.5253397 ],
       [0.12888992, 0.890258  , 0.16950339, 0.8753067 , 0.37186372,
        0.5376426 , 0.51121086, 0.88579243]], dtype=float32)

In [35]:
x = torch.ones(1)
x

tensor([1.])

In [36]:
x.item()

1.0

In [37]:
x = torch.ones(2,2,requires_grad=True)   # requires_grad=True 연산을 추적해준다??

In [38]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [39]:
y = x+1
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [40]:
z = 2*y**2
res = z.mean()
print(res)

tensor(8., grad_fn=<MeanBackward0>)


In [41]:
import torch
import torchvision
import torchvision.transforms as tr
from torch.utils.data import DataLoader, Dataset
import numpy as np

C:\ProgramData\Anaconda3\lib\site-packages\torchvision\io\image.py:11: UserWarning: Failed to load image Python extension: Could not find module 'C:\ProgramData\Anaconda3\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
  warn(f"Failed to load image Python extension: {e}")


In [43]:
transf =tr.Compose([tr.Resize(8),tr.ToTensor()])

trainset = torchvision.datasets.CIFAR10(root = './data', train = True, download=True, transform=transf)
testset = torchvision.datasets.CIFAR10(root = './data', train = False, download=True, transform=transf)


170499072it [00:48, 3520336.56it/s]                               


Extracting ./data\cifar-10-python.tar.gz to ./data
Files already downloaded and verified


In [44]:
trainset[0][0].size()

torch.Size([3, 8, 8])

torch.Size([3, 8, 8]) pytorch에서는 채널 수가 맨 앞에 위치한다. 

In [45]:
trainloader = DataLoader(trainset, batch_size=50, shuffle=True, num_workers=2)
testloader = DataLoader(testset, batch_size=50, shuffle=True, num_workers=2)


In [46]:
len(trainloader)

1000

In [47]:
dataiter = iter(trainloader)
images, labels = dataiter.next()

In [49]:
images.size()

torch.Size([50, 3, 8, 8])

([50, 3, 8, 8]) 
배치  채널 이미지 사이즈(8,8)

In [51]:
transf = tr.Compose([tr.Resize(16),tr.ToTensor()])
trainset = torchvision.datasets.ImageFolder(root = './data',transform=transf)
trainloader = DataLoader(trainset, batch_size=1, shuffle=False, num_workers=2)
print(len(trainloader))

FileNotFoundError: Found no valid file for the classes cifar-10-batches-py. Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp

In [52]:
train_images =np.random.randint(256,size=(20,32,32,3))
train_labels = np.random.randint(2,size = (20,1))

print(train_images.shape, train_labels.shape)

(20, 32, 32, 3) (20, 1)


In [53]:
class TensorData(Dataset):
    
    def __init__(self, x_data, y_data):
        self.x_data = torch.FloatTensor(x_data)
        self.x_data = self.x_data.permute(0,3,1,2)  ###이미지 개수, 채널 수, 이미지 너비, 높이
        self.y_data = torch.LongTensor(y_data)
        self.len = self.y_data.shape[0]
        
    def __getitem__(self, index):
        return self.x_data[index], self.y_data[index]
    
    def __len__(self):
        return self.len
        

In [54]:
train_data = TensorData(train_images, train_labels)
train_loader = DataLoader(train_data, batch_size = 10, shuffle = True)


In [55]:
train_data[0][0].size()

torch.Size([3, 32, 32])

In [56]:
dataiter = iter(train_loader)
images, labels = dataiter.next()

In [57]:
images.size()

torch.Size([10, 3, 32, 32])

class TensorData(Dataset):
    
    def __init__(self, x_data, y_data, transform=None):
        self.x_data = x_data
        self.y_data = y_data
        self.transform = transform
        self.len = len(y_data)
        
    def __getitem__(self, index):
        return self.x_data[index], self.y_data[index]
    
    def __len__(self):
        return self.len