# Numpy
- 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
- 정교한 브로드캐스팅 기능
- 반복문 없이 데이터 배열에 대한 처리를 지원
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

In [1]:
import numpy as np
np.__version__

'1.20.3'

In [7]:
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1],a1[2])
a1[0] = 4
a1[1] = 5 
a1[2] = 6
print(a1)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3
[4 5 6 4 5]


In [11]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)
print(a2.shape)
print(a2[0,0],a2[1,1],a2[2,2,])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [14]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]]])
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


In [15]:
# 배열 생성 및 초기화

In [16]:
# zeros() : 모든 요소를 0으로 초기화
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
# ones() : 모든 요소를 1로 초기화
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
# full() : 모든 요소를 지정한 값으로 초기화
np.full((3,3),1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

In [21]:
# eye() : 단위 행렬 > 정사각형 모양
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [22]:
# tri : 삼각행렬
np.tri(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [24]:
# empty() : 초기화되지 않은 배열 생성 / 초기화가 없어서 배열 생성비용 처렴하고 빠름 / 기존 메모리 위치에 존재하는 값이 있음

np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
# _like(): 지정된 배열과 shape가 같은 행렬
print(a1)
np.zeros_like(a2)

[4 5 6 4 5]


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
np.ones_like(a2)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [29]:
np.full_like(a3, 234)

array([[[234, 234, 234],
        [234, 234, 234],
        [234, 234, 234]],

       [[234, 234, 234],
        [234, 234, 234],
        [234, 234, 234]],

       [[234, 234, 234],
        [234, 234, 234],
        [234, 234, 234]]])

In [30]:
# arange() : 정수 범위로 배열 생성
np.arange(0,32,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [31]:
# linspace() : 범위 내에서 균등 간격의 배열 생성
np.linspace (0 , 1, 5 )

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
# logspace() : 범위 내에서 균등 간격의 로그 스케일로 배열 생성
np.logspace(0.1,1,20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

In [34]:
# random.random() : 랜덤한 수의 배열 생섯
np.random.random((3,3))

array([[0.25638032, 0.37695692, 0.72496496],
       [0.82084119, 0.92742643, 0.44125637],
       [0.57845634, 0.87892264, 0.24963673]])

In [35]:
# random.randint() : 일정 구간의 랜덤 정수의 배열 생성
np.random.randint(0,10,(3,3))


array([[6, 0, 5],
       [3, 5, 6],
       [9, 9, 4]])

In [36]:
# random.normal() : 정규 분포를 고려한 랜덤한 수의 배열 생성
np.random.normal(0,1,(3,3))

array([[ 2.42878241,  1.11034583, -0.93780812],
       [ 0.52390403,  0.89909097, -0.87342519],
       [ 0.49528328, -0.42680337,  0.419048  ]])

In [37]:
# random.rand() : 균등 분포를 고려한 랜덤한 수의 배열 생성
np.random.rand(3,3)

array([[0.79787351, 0.93674207, 0.07121394],
       [0.98194536, 0.47011324, 0.6914247 ],
       [0.68492876, 0.25687277, 0.28196063]])

In [38]:
# random.randn() : 표준 정규 분포를 고려한 랜덤한 수의 배열 생성
np.random.randn(3,3)

array([[ 0.24068756,  0.27794667, -0.23338945],
       [-0.07755771,  0.4750502 ,  0.50256634],
       [-1.01704222, -1.09982131,  0.09414123]])

In [39]:
np.zeros(20,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
np.ones((3,3), dtype= bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [41]:
np.full((3,3),1.0,dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
# 날짜 / 시간배열 생성
data = np.array('2020-01-01', dtype=np.datetime64)
data 
# array('2020-01-01', dtype='datetime64[D]')

array('2020-01-01', dtype='datetime64[D]')

In [48]:
data + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [50]:
datetime = np.datetime64('2020-06-01 13:00')
datetime

numpy.datetime64('2020-06-01T13:00')

In [53]:
datatime = np.datetime64('2020-06-01 12:00:12.34', 'ns')
datatime

numpy.datetime64('2020-06-01T12:00:12.340000000')

In [54]:
def array_info(array):
    print(array)
    print('ndim :', array.ndim)
    print('shape :',array.shape)
    print('dtype :', array.size)
    print('itemsize :', array.itemsize)
    print('nbyte:',array.nbytes)
    print('stride :', array.strides)

In [55]:
array_info(a1)

[4 5 6 4 5]
ndim : 1
shape : (5,)
dtype : 5
itemsize : 4
nbyte: 20
stride : (4,)


In [56]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim : 2
shape : (3, 3)
dtype : 9
itemsize : 4
nbyte: 36
stride : (12, 4)
