# Numpy
Numerical Python의 약자
고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
범용적 데이터 저리에 사용 가능한 다차원 컨테이너
정교한 브로드캐스팅 가능
파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음


In [2]:
import numpy as np 
np.__version__

'1.19.5'

# 배열 생성 

1차원  : 축이 없다.
2차원 : 축이 두 개가 있다. (0,1)
3차원 : 축이 세 개가 된다. (0,1,2)

In [3]:
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))

#<class 'numpy.ndarray'> nd : 차원을 의미한다.
print(a1.shape)  # (5,) 5개의 element가 있다.
print(a1[0], a1[1],a1[2], a1[3],a1[4])  # 1 2 3 4 5
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


In [4]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])  # 2차원은 리스트 안에 리스트로 표현
print(a2)
print(a2.shape)  # (3, 3)
print(a2[0,0],a2[1,1],a2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [5]:
# 3차원 표현
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
              [[1,2,3],[4,5,6],[7,8,9]],
              [[1,2,3],[4,5,6],[7,8,9]]])
print(a3)
print(a3.shape)  # (3, 3, 3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


In [6]:
# 배열 생성 및 초기화
# 모든 요소를 0으로 초기화
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
# 모든 요소를 1로 초기화
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# 모든 요소를 지정한 값으로 초기화
np.full((3,3),1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

In [13]:
# eye 단위행렬 생성 : 주 대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
# 삼각행렬
np.tri(5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [17]:
# 초기화되지 않은 배열 생성
# 초기화가 없어서 배열 생성비용 저렴하고 빠름
# '' 기존 메모리 위치에 존재하는 값이 있음
np.empty(10)        

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
# _like
print(a1)
np.zeros_like (a1)

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [21]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [22]:
print(a3)
np.full_like(a3,10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])