# 4. 파이토치 기본
## 4.1 텐서

In [1]:
import torch
import numpy as np

In [2]:
x = torch.empty(5,4)

In [3]:
print(x)

tensor([[4.2862e+17, 3.0796e-41, 7.0065e-44, 6.8664e-44],
        [6.3058e-44, 6.8664e-44, 6.8664e-44, 6.3058e-44],
        [6.7262e-44, 7.7071e-44, 1.1771e-43, 6.8664e-44],
        [7.1466e-44, 8.1275e-44, 7.0065e-44, 7.1466e-44],
        [8.1275e-44, 7.0065e-44, 6.7262e-44, 6.4460e-44]])


In [4]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [5]:
torch.zeros(2)

tensor([0., 0.])

In [6]:
torch.rand(5,6)

tensor([[0.8138, 0.0677, 0.7491, 0.7262, 0.6369, 0.4906],
        [0.2219, 0.5956, 0.6686, 0.3414, 0.5864, 0.9827],
        [0.9121, 0.1366, 0.7165, 0.0373, 0.4957, 0.3994],
        [0.3440, 0.6306, 0.9550, 0.8893, 0.9882, 0.4796],
        [0.2105, 0.0202, 0.2900, 0.5107, 0.8357, 0.0565]])

In [7]:
l = [13,4]
r = np.array([4,56,7])

In [8]:
torch.tensor(l)

tensor([13,  4])

In [9]:
torch.tensor(r)

tensor([ 4, 56,  7])

In [10]:
x.size()

torch.Size([5, 4])

In [11]:
x.size()[1]

4

In [12]:
x.size(1)

4

In [13]:
type(x)

torch.Tensor

In [14]:
x = torch.rand(2,2) # 2x2 랜덤 행렬
y = torch.rand(2,2) # 2x2 랜덤 행렬
x+y

tensor([[1.1871, 1.5943],
        [0.9184, 0.4019]])

In [15]:
torch.add(x,y)

tensor([[1.1871, 1.5943],
        [0.9184, 0.4019]])

In [16]:
y.add(x)

tensor([[1.1871, 1.5943],
        [0.9184, 0.4019]])

In [17]:
y.add_(x)

tensor([[1.1871, 1.5943],
        [0.9184, 0.4019]])

In [18]:
x = torch.rand(8,8)
print(x.size())

torch.Size([8, 8])


In [19]:
a = x.view(64)
print(a.size())

torch.Size([64])


In [20]:
b = x.view(-1,4,4)
print(b.size())

torch.Size([4, 4, 4])


In [21]:
y = x.numpy()
type(y)

numpy.ndarray

In [22]:
x = torch.ones(1)
print(x.item())

1.0
