# 텐서 Tensor
- 텐서(tensor)는 배열(array)이나 행렬(matrix)과 매우 유사한 특수한 자료구조
- 모델의 입력(input)과 출력(output), 그리고 모델의 매개변수들을 부호화(encode)한다.
-  NumPy 의 ndarray와 유사

In [1]:
import torch
import numpy as np

In [4]:
# 텐서 초기화
# 데이터로부터 직접(directly) 생성하기
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)
# NumPy 배열로부터 생성하기
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)


tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [5]:
# 텐서의 속성 : 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지 나타냄
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [6]:
# 텐서 합치기
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.8820, 0.4872, 0.3195, 0.1853, 0.8820, 0.4872, 0.3195, 0.1853, 0.8820,
         0.4872, 0.3195, 0.1853],
        [0.8187, 0.6089, 0.4049, 0.7483, 0.8187, 0.6089, 0.4049, 0.7483, 0.8187,
         0.6089, 0.4049, 0.7483],
        [0.5991, 0.7219, 0.6848, 0.8667, 0.5991, 0.7219, 0.6848, 0.8667, 0.5991,
         0.7219, 0.6848, 0.8667]])
