In [1]:
import tensorflow as tf

In [2]:
x_train_uni = [[[1], [2]], [[3], [4]], [[5], [6]]]
y_train_uni = [0.1, 0.2, 0.3]

train_univariate = tf.data.Dataset.from_tensor_slices((x_train_uni, y_train_uni))
print(train_univariate)
print(list(train_univariate))

<TensorSliceDataset shapes: ((2, 1), ()), types: (tf.int32, tf.float32)>
[(<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [2]])>, <tf.Tensor: shape=(), dtype=float32, numpy=0.1>), (<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[3],
       [4]])>, <tf.Tensor: shape=(), dtype=float32, numpy=0.2>), (<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[5],
       [6]])>, <tf.Tensor: shape=(), dtype=float32, numpy=0.3>)]


In [ ]:
train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))  
# .from_tensor_slices : 첫 번째 차원을 따라 슬라이스 된다. 
# // 입력 텐서의 구조를 유지하고 각 텐서의 첫 번째 차원을 제거하고 
# 이를 데이터 세트 차원으로 사용한다. 
# 쉽게 말하면 데이터 셋을 구성한다고 볼 수 있음

train_dataset = (
    train_dataset.map(
        encode_single_sample, num_parallel_calls=tf.data.AUTOTUNE
    )
    # dataset.map : 요소별 변환
    # dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
    # dataset = dataset.map(lambda x: x*2)
    # 출력값이 [2,4,6] 으로 변환
    .batch(batch_size)  # .batch : 데이터 배치의 크기를 설정 
    # .take() 해당 배치를 몇 번 불러올지 결정
    .prefetch(buffer_size=tf.data.AUTOTUNE)  
    # .prefetch : 연산에 필요한 data를 미리 가져오는 것, memory latency를 숨길 수 있다.
    # cpu가 연산을 하는 동안 다음 연산에 필요한 데이터를 유추한다는 것
    # 쉽게 말해서 빠른 연산을 진행 할 수 있도록 도와준다.
)

validation_dataset = tf.data.Dataset.from_tensor_slices((x_valid, y_valid))
validation_dataset = (
    validation_dataset.map(
        encode_single_sample, num_parallel_calls=tf.data.AUTOTUNE
    )
    .batch(batch_size)
    .prefetch(buffer_size=tf.data.AUTOTUNE)
)